server:
  port: 9095
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
    min-SpareThreads: 20
    acceptCount: 700
spring:
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  application:
    name: alibaba-cloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    root: info
    com.example: debug